version: '3'
services:
  db:
    image: rethinkdb:latest
    ports:  
    - "38080:8080"
    - "28015:28015"
    - "29015:29015"
    networks:
      - lms
    volumes:
      - /data:/data

  server:
    build: ./backend
    ports: 
      - "5400:5400"
    depends_on: 
      - db
    volumes: 
      - ./:/server
    networks: 
      - lms
networks:
  lms:
volumes: 
  data:


#   web:
#     image: node:alpine    
#     volumes:
#       - ./startup:/usr/startup
#       - ./src/app:/usr/src/app
#     working_dir: /usr/src/app
#     environment:
#       - NPM_PROXY_CACHE=${MINIENV_NPM_PROXY_CACHE}
#     command: /usr/startup/startup.sh
#     ports:
#       - "33000:3000"
#     depends_on:
#       - db